using ClinicManager.Shared.DTO_s.Records;
using ClinicManager.Shared.DTO_s.Records.Elimination;
using ClinicManager.Shared.DTO_s.Records.FluidBalance;
using ClinicManager.Shared.DTO_s.Records.Hygiene;
using ClinicManager.Shared.DTO_s.Records.Intervention;
using ClinicManager.Shared.DTO_s.Records.Mobility;
using ClinicManager.Shared.DTO_s.Records.Nutrition;
using ClinicManager.Shared.DTO_s.Records.Observations;
using ClinicManager.Shared.DTO_s.Records.Oxygenation;
using ClinicManager.Shared.DTO_s.Records.Prescription;
using ClinicManager.Shared.DTO_s.Records.Psychological;
using ClinicManager.Shared.DTO_s.Records.Safety;
using ClinicManager.Shared.DTO_s.Records.SkinIntegrity;
using ClinicManager.Shared.DTO_s.Records.SkinReport;
using ClinicManager.Shared.Wrappers;

namespace ClinicManager.Web.Infrastructure.Services.PatientRecords
{
    public interface IPatientRecordService
    {
        Task<IResult<int>> AddComfortSleepRecord(ComfortSleepReportDTO request);
        Task<IResult<int>> AddDailyCareRecord(DailyCareRecordDTO request);
        Task<IResult<int>> AddCathetherRecord(CathetherDTO request);
        Task<IResult<int>> AddContinentRecord(ContinentDTO request);
        Task<IResult<int>> Add24HourIntakeRecord(Previous24HourIntakeDTO request);
        Task<IResult<int>> AddOralInputTestRecord(OralIntakeDTO request);
        Task<IResult<int>> AddOralOutputTestRecord(OralOutputDTO request);
        Task<IResult<int>> AddIVTestRecord(FluidBalanceIVCheckDTO request);
        Task<IResult<int>> AddBedBathAssist(BedBathAssistDTO request);
        Task<IResult<int>> AddBedBathRecord(BedBathDTO request);
        Task<IResult<int>> AddSelfCareRecord(SelfCareDTO request);
        Task<IResult<int>> AddIsolationRecord(IsolationDTO request);
        Task<IResult<int>> AddMedicationRecord(MedicationDTO request);
        Task<IResult<int>> AddPostOperativeCareRecord(PostOperativeCareDTO request);
        Task<IResult<int>> AddTractionRecord(TractionDTO request);
        Task<IResult<int>> AddWoundCareRecord(WoundCareDTO request);
        Task<IResult<int>> AddAssistInChairRecord(AssistIntoChairDTO request);
        Task<IResult<int>> AddBedRestRecord(BedRestDTO request);
        Task<IResult<int>> AddExerciseRecord(ExerciseDTO request);
        Task<IResult<int>> AddMobileImmobileRecord(MobileImmobileDTO request);
        Task<IResult<int>> AddWalkAssistanceRecord(WalkWithAssistanceDTO request);
        Task<IResult<int>> AddFullWardDietRecord(FullWardDietDTO request);
        Task<IResult<int>> AddNPORecord(KeepNPODTO request);
        Task<IResult<int>> AddSpecialRecord(SpecialDTO request);
        Task<IResult<int>> AddBloodFrequencyRecord(BloodDTO request);
        Task<IResult<int>> AddBloodGlucoseRecord(BloodGlucoseDTO request);
        Task<IResult<int>> AddNeuroLogicalRecord(NeuroLogicalDTO request);
        Task<IResult<int>> AddNeuroVascularRecord(NeuroVascularDTO request);
        Task<IResult<int>> AddUrineTestRecord(UrineTestDTO request);
        Task<IResult<int>> AddVitalSignRecord(VitalSignDTO request);
        Task<IResult<int>> AddInhalaNebsRecord(InhalaNebsDTO request);
        Task<IResult<int>> AddMaskTimeRecord(MaskDTO request);
        Task<IResult<int>> AddNasalCannulRecord(NasalCannulaDTO request);
        Task<IResult<int>> AddPolyMaskRecord(PolyMaskDTO request);
        Task<IResult<int>> AddProgressReportRecord(ProgressReportDTO request);
        Task<IResult<int>> AddCommunicationRecord(CommunicationDTO request);
        Task<IResult<int>> AddHealthEducationRecord(HealthEducationDTO request);
        Task<IResult<int>> AddSupportRecord(SupportDTO request);
        Task<IResult<int>> AddCheckIDBandsRecord(CheckIDBandDTO request);
        Task<IResult<int>> AddCotsideRecord(CotsideDTO request);
        Task<IResult<int>> AddSkinIntegrityReportRecord(SkinReportDTO request);
        Task<IResult<int>> AddPressurePartCareTimeRecord(PressurePartCareDTO request);
        Task<IResult<int>> AddRednessReportRecord(RednessDTO request);
        Task<IResult<int>> AddStoolChartRecord(StoolChartDTO request);
        Task<IResult<int>> AddPrescription(PrescriptionDTO request);


        Task<IResult<List<PrescriptionDTO>>> GetAllPrescriptionByPatientId(int patientId);
        Task<IResult<List<ComfortSleepReportDTO>>> GetAllComfortSleepRecordsByPatientId(int patientId);
        Task<IResult<List<DailyCareRecordDTO>>> GetAllDailyCareRecordsByPatientId(int patientId);
        Task<IResult<List<CathetherDTO>>> GetAllCathethersByPatientId(int patientId);
        Task<IResult<List<ContinentDTO>>> GetAllContinentsByPatientId(int patientId);
        Task<IResult<List<Previous24HourIntakeDTO>>> GetAll24HourIntakesByPatientId(int patientId);
        Task<IResult<List<OralIntakeDTO>>> GetAllOralIntakeChecksByPatientId(int patientId); 
        Task<IResult<List<OralOutputDTO>>> GetAllOralOutputChecksByPatientId(int patientId); 
        Task<IResult<List<FluidBalanceIVCheckDTO>>> GetAllIVCheckByPatientId(int patientId);
        Task<IResult<List<BedBathAssistDTO>>> GetAllBedBathAssistRecordsByPatientId(int patientId);
        Task<IResult<List<BedBathDTO>>> GetAllBedBathRecordByPatientId(int patientId);
        Task<IResult<List<SelfCareDTO>>> GetAllSelfCareRecordsByPatientId(int patientId);
        Task<IResult<List<IsolationDTO>>> GetAllIsolationRecordsByPatientId(int patientId);
        Task<IResult<List<MedicationDTO>>> GetAllMedicationRecordsByPatientId(int patientId);
        Task<IResult<List<PostOperativeCareDTO>>> GetAllPostOperativeCareRecordsByPatientId(int patientId);
        Task<IResult<List<TractionDTO>>> GetAllTractionRecordsByPatientId(int patientId);
        Task<IResult<List<WoundCareDTO>>> GetAllWoundCareRecordsByPatientId(int patientId);
        Task<IResult<List<AssistIntoChairDTO>>> GetAllAssistInChairRecordByPatientId(int patientId);
        Task<IResult<List<BedRestDTO>>> GetAllBedRestRecordsByPatientId(int patientId);
        Task<IResult<List<ExerciseDTO>>> GetAllExerciseRecordsByPatientId(int patientId);
        Task<IResult<List<MobileImmobileDTO>>> GetAllByMobilityRecordsByPatientId(int patientId);
        Task<IResult<List<WalkWithAssistanceDTO>>> GetAllWalkAssistanceRecordsByPatientId(int patientId);
        Task<IResult<List<FullWardDietDTO>>> GetAllFullWardDietByPatientId(int patientId);
        Task<IResult<List<KeepNPODTO>>> GetAllNPORecordByPatientId(int patientId);
        Task<IResult<List<SpecialDTO>>> GetAllSpecialRecordsByPatientId(int patientId);
        Task<IResult<List<BloodGlucoseDTO>>> GetAllBloodGlucoseRecordsByPatientId(int patientId);
        Task<IResult<List<BloodDTO>>> GetAllBloodFrequencyRecordsByPatientId(int patientId);
        Task<IResult<List<NeuroLogicalDTO>>> GetAllNeuroLogicalRecordsByPatientId(int patientId);
        Task<IResult<List<NeuroVascularDTO>>> GetAllNeuroVascularPatientId(int patientId);
        Task<IResult<List<UrineTestDTO>>> GetAllUrineTestsByPatientId(int patientId);
        Task<IResult<List<VitalSignDTO>>> GetAllVitalSignRecordsByPatientId(int patientId);
        Task<IResult<List<InhalaNebsDTO>>> GetAllInhalaByPatientId(int patientId);
        Task<IResult<List<MaskDTO>>> GetAllMaskByPatientId(int patientId);
        Task<IResult<List<NasalCannulaDTO>>> GetAllNassalCannulRecordsByPatientId(int patientId);
        Task<IResult<List<PolyMaskDTO>>> GetAllPolyMaskByPatientId(int patientId);
        Task<IResult<List<ProgressReportDTO>>> GetAllProgressReportsByPatientId(int patientId);
        Task<IResult<List<CommunicationDTO>>> GetAllCommunicationRecordsByPatientId(int patientId);
        Task<IResult<List<HealthEducationDTO>>> GetAllHealthEducationByPatientId(int patientId);
        Task<IResult<List<SupportDTO>>> GetAllSupportRecordsByPatientId(int patientId);
        Task<IResult<List<CheckIDBandDTO>>> GetAllCheckIDBandRecordsByPatientId(int patientId);
        Task<IResult<List<CotsideDTO>>> GetAllCotsideRecordsByPatientId(int patientId);
        Task<IResult<List<SkinReportDTO>>> GetAllSkinReportsByPatientId(int patientId);
        Task<IResult<List<PressurePartCareDTO>>> GetAllPressurePartCareTimeByPatientId(int patientId);
        Task<IResult<List<RednessDTO>>> GetAllRednessReportsById(int patientId);
        Task<IResult<List<StoolChartDTO>>> GetAllStoolChartsByPatientId(int patientId);

        Task<IResult<PrescriptionDTO>> GetPrescriptionByPatientId(int id);
        Task<IResult<ComfortSleepReportDTO>> GetComfortSleepRecordByPatientId(int id);
        Task<IResult<DailyCareRecordDTO>> GetDailyCareRecordByPatientId(int id);
        Task<IResult<CathetherDTO>> GetCathetherRecordByPatientId(int id);
        Task<IResult<ContinentDTO>> GetContinentByPatientId(int id);
        Task<IResult<Previous24HourIntakeDTO>> Get24HourIntakeByPatientId(int id);
        Task<IResult<OralIntakeDTO>> GetOralCheckByPatientId(int id); //
        Task<IResult<FluidBalanceIVCheckDTO>> GetIVCheckByPatientId(int id);
        Task<IResult<BedBathAssistDTO>> GetBedBathAssistByPatientId(int id);
        Task<IResult<BedBathDTO>> GetBedBathPatientId(int id);
        Task<IResult<SelfCareDTO>> GetSelfCareRecordByPatientId(int id);
        Task<IResult<IsolationDTO>> GetIsolationRecordByPatientId(int id);
        Task<IResult<MedicationDTO>> GetMedicationRecordByPatientId(int id);
        Task<IResult<PostOperativeCareDTO>> GetPostOperativeRecordByPatientId(int id);
        Task<IResult<TractionDTO>> GetTractionByPatientId(int id);
        Task<IResult<WoundCareDTO>> GetWoundCareByPatientId(int id);
        Task<IResult<AssistIntoChairDTO>> GetAssistInChairRecordByPatientId(int id);
        Task<IResult<BedRestDTO>> GetBedRestRecordByPatientId(int id);
        Task<IResult<MobileImmobileDTO>> GetMobilityRecordByPatientId(int id);
        Task<IResult<ExerciseDTO>> GetExerciseRecordByPatientId(int id);
        Task<IResult<WalkWithAssistanceDTO>> GetWalkAssistanceByPatientId(int id);
        Task<IResult<FullWardDietDTO>> GetFullWardDietByPatientId(int id);
        Task<IResult<KeepNPODTO>> GetNPORecordByPatientId(int id);
        Task<IResult<SpecialDTO>> GetSpecialRecordPatientId(int id);
        Task<IResult<BloodDTO>> GetBloodFrequencyRecordByPatientId(int id);
        Task<IResult<BloodGlucoseDTO>> GetBloodGlucoseRecordByPatientId(int id);
        Task<IResult<NeuroLogicalDTO>> GetNeuroLogicalRecordByPatientId(int id);
        Task<IResult<NeuroVascularDTO>> GetNeuroVascularRecordByPatientId(int id);
        Task<IResult<UrineTestDTO>> GetUrineTestByPatientId(int id);
        Task<IResult<VitalSignDTO>> GetVitalSignRecordByPatientId(int id);
        Task<IResult<InhalaNebsDTO>> GetInhalaRecordByPatientId(int id);
        Task<IResult<MaskDTO>> GetMaskRecordByPatientId(int id);
        Task<IResult<NasalCannulaDTO>> GetNassalCannulByPatientId(int id);
        Task<IResult<PolyMaskDTO>> GetPolyMaskRecordByPatientId(int id);
        Task<IResult<ProgressReportDTO>> GetProgressReportByPatientId(int id);
        Task<IResult<CommunicationDTO>> GetCommunicationRecordByPatientId(int id);
        Task<IResult<HealthEducationDTO>> GetHealthEducationByPatientId(int id);
        Task<IResult<SupportDTO>> GetSupportRecordByPatientId(int id);
        Task<IResult<CheckIDBandDTO>> GetCheckIDBandRecordByPatientId(int id);
        Task<IResult<CotsideDTO>> GetCotsideByPatientId(int id);
        Task<IResult<SkinReportDTO>> GetSkinReportByPatientId(int id);
        Task<IResult<PressurePartCareDTO>> GetPressurePartTimeRecordByPatientId(int id);
        Task<IResult<RednessDTO>> GetRednessRecordByPatientId(int id);
        Task<IResult<StoolChartDTO>> GetStoolChartByPatientIdQuery(int id);
    }
}
